# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1332 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.33.2"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.2/astro_1.33.2_darwin_arm64.tar.gz"
      sha256 "3601f0f94cde02fe45babfb787986c78e1811b63cfc1a24c9329b8b30b00a333"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.2/astro_1.33.2_darwin_amd64.tar.gz"
      sha256 "e109970bbe02b579121dd1d70566125b889ed8c1f46c88d4ebcd9b78ab2ac036"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.2/astro_1.33.2_linux_arm64.tar.gz"
      sha256 "5ed6ae1c9b1b2743152904934035e6e40f4889f19fbe0a219194635f82ed160e"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.2/astro_1.33.2_linux_amd64.tar.gz"
      sha256 "d39cb83de7030f72e8c121e34286eecf6bf7c1d28bf444e10d0ba6c8f84afa45"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
