# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0131 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.16.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.16.0/astro_0.16.0_darwin_amd64.tar.gz"
    sha256 "19a03256837898a412803af9b539c8baa48b1b6642844b210fa52009c1a31dd9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.16.0/astro_0.16.0_linux_386.tar.gz"
      sha256 "9bb7f0dd7d9abb6ecc5fbc6063a8acf26c5d86eb23a2828de1a4795423af5172"
    end
  end
  
  depends_on "go"

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
