# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1350 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.35.0"
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.35.0/astro_1.35.0_darwin_arm64.tar.gz"
      sha256 "496790abe290dbb860c2ac4fd5d2741240ee0eecb1d06d8b0a5fceff2b58d848"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.35.0/astro_1.35.0_darwin_amd64.tar.gz"
      sha256 "9f179842d642e57c13c159e70c0f65f87a4d98d79682d1ac56a04752392c6c18"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.35.0/astro_1.35.0_linux_arm64.tar.gz"
      sha256 "d0119f3087c091928dc00537a96de8e60d41a39b1e81477180107217a60a3f15"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.35.0/astro_1.35.0_linux_amd64.tar.gz"
      sha256 "06b009db241e3f938c7ce08c6ddebf1d888bd49c6db193f4025e232e0582fd79"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
