# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0164 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.16.4"

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.16.4/astro_0.16.4_darwin_amd64.tar.gz"
    sha256 "d4231cb1ffbafad407344f50979d2d9e2ee1cdf897e062fec60fcd1c1e49ac51"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.16.4/astro_0.16.4_linux_amd64.tar.gz"
      sha256 "6b80e6288cbfe7039e8f348cb0d414e77d09dda50094aead4e05fc3a99e0da9e"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
