# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1460 < Formula
  desc "To build and run Airflow Dags locally via docker-compose and deploy Dags to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.46.0"

  depends_on "podman" => :recommended if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.46.0/astro_1.46.0_darwin_amd64.tar.gz"
      sha256 "e67c4fdd8c592e86cb42be5f3e096eda36cbe736d36c8838c68edb5f245d5d5f"

      define_method(:install) do
        bin.install "astro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.46.0/astro_1.46.0_darwin_arm64.tar.gz"
      sha256 "c3e34d3bfa5b7449aa2c37416b8aa6d90e9cf98da1a8bb51ccb438379056c62e"

      define_method(:install) do
        bin.install "astro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.46.0/astro_1.46.0_linux_amd64.tar.gz"
      sha256 "bf63dfbfc8373317d0aa0abdd6307f75c3890c0691483470c682054516f79dcf"
      define_method(:install) do
        bin.install "astro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.46.0/astro_1.46.0_linux_arm64.tar.gz"
      sha256 "f69675aad852fc52e219217d28c066dc5a8e77eee457e1b5acfac1c615085be1"
      define_method(:install) do
        bin.install "astro"
      end
    end
  end

  test do
    system "#{bin}/astro version"
  end
end
