# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1370 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.37.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.37.0/astro_1.37.0_darwin_arm64.tar.gz"
      sha256 "824da0e1fe8d88115951d1ac48fbaa2449a7451bdc64cdd586bb2280fc781106"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.37.0/astro_1.37.0_darwin_amd64.tar.gz"
      sha256 "d9b79403ca409ce5bcedae300a37e05517b665abe69e21247a9f10f5ece16a93"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.37.0/astro_1.37.0_linux_arm64.tar.gz"
      sha256 "d7d49d2e4e2ef8f52aef041049e6100708783d04b9e94f00709e8bc0cda59bcf"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.37.0/astro_1.37.0_linux_amd64.tar.gz"
      sha256 "cb8682972f5c8dd34436bd54ffafe65dd12766e6864b3c893413da092a983edd"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
