# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1290 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.29.0/astro_1.29.0_darwin_arm64.tar.gz"
        sha256 "c12685b7f6737dfb7eadff0936c01f50c3306a7af35e01443a3b188dca197f3d"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.29.0/astro_1.29.0_darwin_amd64.tar.gz"
        sha256 "d6a03d53511b74cae9aff193d567fe1c4791cc03e235a9623532a7aad9e32370"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.29.0/astro_1.29.0_linux_arm64.tar.gz"
        sha256 "106fbd120b245ee3fb882910b7a38d1072cbe9c0b8819fbdcfa098fabe3fb398"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.29.0/astro_1.29.0_linux_amd64.tar.gz"
        sha256 "afc4126cef417519fca74b1d20973e9eb5cf0362ca58edb812f33126b7a17928"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
