# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1360 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.36.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.36.0/astro_1.36.0_darwin_arm64.tar.gz"
      sha256 "8a394a12f684f8c5a13d85a8fc245f655526be82f4e7b0c5071315e895e09d1a"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.36.0/astro_1.36.0_darwin_amd64.tar.gz"
      sha256 "e3bb0a347a618744d80fdfa224375d2040dc44826bcca50c3dad706aa354ef56"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.36.0/astro_1.36.0_linux_arm64.tar.gz"
      sha256 "9b01a4d42622bd5b20e66ffc2f2c5d42e9a8a0e6b2980b53d913c0cc7ef998f9"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.36.0/astro_1.36.0_linux_amd64.tar.gz"
      sha256 "b4e4f61968de0748f4f3c97dd34f42e8923e09fcd66b2f0d31768a07a8665fcd"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
