# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1420 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.42.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.0/astro_1.42.0_darwin_arm64.tar.gz"
      sha256 "57d0d94f42c8c8b6ce659dc508b67a4ad284a0f59ac80c4508fca595f711131d"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.0/astro_1.42.0_darwin_amd64.tar.gz"
      sha256 "9f906629b22a7d12882c3461a1f8c67b3c238c51f251269707d6b7706471ec52"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.0/astro_1.42.0_linux_arm64.tar.gz"
      sha256 "a891c4853c2b44f944547e72a223c60978c07825c43ef3e249a9fb91e2770682"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.0/astro_1.42.0_linux_amd64.tar.gz"
      sha256 "bf42a29eb2479b5fa7de8544953bdc868557967651f26a4ed6b64f9b9f710a8c"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
