# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1150 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.15.0/astro_1.15.0_darwin_arm64.tar.gz"
        sha256 "e56f3f0423c4331c7dfe9c9e1720c4669f3090d43bb42748446396a6aef18479"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.15.0/astro_1.15.0_darwin_amd64.tar.gz"
        sha256 "58eb82424fea5d6185594f7f55bda3bef3e3bc24074113daf8bb6f14944e8754"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.15.0/astro_1.15.0_linux_arm64.tar.gz"
        sha256 "9e4aa682133c99c117e62c396dcce2a30906e995d262f972fcb9e1e1e8121421"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.15.0/astro_1.15.0_linux_amd64.tar.gz"
        sha256 "616a40a33408d12853668827fcb1959f4b3e7348a865f9a52c5ef50526585b55"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
