# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1320 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.32.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.32.0/astro_1.32.0_darwin_arm64.tar.gz"
      sha256 "7a0d0e622f9d7ea47f90a987d801b6485f299d6b046f9e1abc6928142a096ae6"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.32.0/astro_1.32.0_darwin_amd64.tar.gz"
      sha256 "95dd6d83554d010a175abeea2c47bf4ec486af862fe00b3f178f987d3f606ead"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.32.0/astro_1.32.0_linux_arm64.tar.gz"
      sha256 "0e5ddcdd5a5ddf6ab1b2d6fbd6085ee963334da6ffc9a058909da15a11d990f7"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.32.0/astro_1.32.0_linux_amd64.tar.gz"
      sha256 "77418ae7c9ff74b7e3c07a281a8f4eee2ff07069dd18f0aa5c080ad28caa1adb"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
