# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1331 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.33.1"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.1/astro_1.33.1_darwin_arm64.tar.gz"
      sha256 "b08c7d751f8a01268eb5000c2d5b2a452ff591dd8fe36720ac8da26d222564bb"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.1/astro_1.33.1_darwin_amd64.tar.gz"
      sha256 "03f342243833706b8c7fbb3c17e63487397cb45cde0b0f28e3fc8b8e07fa7183"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.1/astro_1.33.1_linux_arm64.tar.gz"
      sha256 "5a8ab7a794590981c7b7c73a29399fcebaf0c5f0311b1df3495d29e6b7069344"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.1/astro_1.33.1_linux_amd64.tar.gz"
      sha256 "06b813585b91042fb92f9304da8118c40104706b11993c8ad7630fb3b96610c7"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
