# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0272 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.27.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.27.2/astro_0.27.2_darwin_arm64.tar.gz"
      sha256 "763bec431a12e41c04be53dda521738161486426db96501d67b40850a9498be0"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.27.2/astro_0.27.2_darwin_amd64.tar.gz"
      sha256 "338df26c174e298b5f08a688b9ab0dc210c19f2e02e0071cd384cfc94d44c22d"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.27.2/astro_0.27.2_linux_arm64.tar.gz"
      sha256 "f58973944825602ec96c0c2245863788fd351dc87ca76603b0e16e6985eef81f"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.27.2/astro_0.27.2_linux_amd64.tar.gz"
      sha256 "e9dbe93d54cc21ffe13b6381222e940778e55590be4adbfde9949a1965337dd1"
    end
  end

  def install
    bin.install "astro"
  end


  test do
    system "#{bin}/astro version"
  end
end
