# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT181 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "1.8.0"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.1/astro_1.8.1_darwin_arm64.tar.gz"
        sha256 "f7a2f0e827d86cc366c4295886b473bebad07f0ec4dad337a4bad0f174327be4"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.1/astro_1.8.1_darwin_amd64.tar.gz"
        sha256 "709044460d7159b72e54ff086eaab84d3ca1ac0621cdea246faebf75d95c3d54"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.1/astro_1.8.1_linux_arm64.tar.gz"
        sha256 "506264035838ca3cfdc27420eb866164a055d3c0ffcda2292c746a2a6ed3e633"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.1/astro_1.8.1_linux_amd64.tar.gz"
        sha256 "0d3cffcf6323ab99afd7c69df2185211395e1757b3b0e0786cc51f73127d6ef4"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
