# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0281 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "0.28.1"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.1/astro_0.28.1_darwin_arm64.tar.gz"
        sha256 "e82073f42a93fc82852833e31439a542d13ac9b68b2295df94a864d072fa06f6"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.1/astro_0.28.1_darwin_amd64.tar.gz"
        sha256 "47c3e7229663370785cfd7c47c09ff753e79d049194fe69397e783914706cd77"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.1/astro_0.28.1_linux_arm64.tar.gz"
        sha256 "dac71a969b80d6ddda811832fe01a26bdb7223bd36103aab02e10e779e94c1ec"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.1/astro_0.28.1_linux_amd64.tar.gz"
        sha256 "9170ed91656fd7fb9cba9343573e87eea335cae09ebf0fd24099de6bfc8a912a"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end