# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT184 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.4/astro_1.8.4_darwin_arm64.tar.gz"
        sha256 "d026b1125e664b521c9bbaa8b2b6769b1036d5b13832b49cbbe40b80573c0467"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.4/astro_1.8.4_darwin_amd64.tar.gz"
        sha256 "c4950bb93f2b52da277e37ba075bc6ff8647a46da760ab8035dd2874d590f977"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.4/astro_1.8.4_linux_arm64.tar.gz"
        sha256 "d161db85e650d95eed9ba73c583ecdc337525bb72374c29d8309e96cf035f27a"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.4/astro_1.8.4_linux_amd64.tar.gz"
        sha256 "ddd23c0baf6975b74b504822a6b1bddd51c082359b3feb25bd653769af65e608"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
