# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0162 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.16.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.16.2/astro_0.16.2_darwin_amd64.tar.gz"
    sha256 "6ddb8bf91847dee9d416a02b52a860ae476cae0283d0265bbdb89adfb3296953"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.16.2/astro_0.16.2_linux_386.tar.gz"
      sha256 "659928709bfe32a86c7368a151053f61eca9c74c3ab5bdcbfa29966a939205a1"
    end
  end
  
  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
