# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0270 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "0.27.0"
  
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.0/astro_0.27.0_darwin_amd64.tar.gz"
        sha256 "b6aed7745808c8fcea24e2f2a90e9b5a0164621619c8ba68d833242f8c3e09da"
      end
    end
  
    on_linux do
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.0/astro_0.27.0_linux_amd64.tar.gz"
        sha256 "8615447fde22750dc4c61bb98375fd312c23aaa94513b7b686992d8569ff9747"
      end
    end
  
    def install
      bin.install "astro"
    end
  
    test do
      system "#{bin}/astro version"
    end
  end
