# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1190 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.19.0/astro_1.19.0_darwin_arm64.tar.gz"
        sha256 "9efb9c07680819901df7dfe9bf32c59edd12a46799bb148eccc9914107144e5b"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.19.0/astro_1.19.0_darwin_amd64.tar.gz"
        sha256 "3d4b8058a1b8c4d88ff8c828b9c542332aeab9bd644d74f0a24572b88613052a"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.19.0/astro_1.19.0_linux_arm64.tar.gz"
        sha256 "f00655537c9491726b3095c16612f2a9956ec7987aa4cfb8071ea42c4bddec67"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.19.0/astro_1.19.0_linux_amd64.tar.gz"
        sha256 "d8c1262d929f57506b7c0ab2b86472f2184f14c0fd29e1d522015e32caa45bdb"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
