# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1450 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.45.0"

  depends_on "podman" => :recommended if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.45.0/astro_1.45.0_darwin_amd64.tar.gz"
      sha256 "1a580936d728bfbdcdaa56bfc738ef1ecaa65c80c9d3133620bbf1145a6ac852"

      define_method(:install) do
        bin.install "astro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.45.0/astro_1.45.0_darwin_arm64.tar.gz"
      sha256 "d566f8a5194ee631b212018baf8ac00ab8a4fe628c23ccd614878b8208221380"

      define_method(:install) do
        bin.install "astro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.45.0/astro_1.45.0_linux_amd64.tar.gz"
      sha256 "8455342dc97f061492a39306b8de5ccfe090080acff70db52d5244e0c1b52bec"
      define_method(:install) do
        bin.install "astro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.45.0/astro_1.45.0_linux_arm64.tar.gz"
      sha256 "bdce34dbe739f294e0c13fb2ad2ccd530f37f3e95c7afb2519c226ade0a450b7"
      define_method(:install) do
        bin.install "astro"
      end
    end
  end

  test do
    system "#{bin}/astro version"
  end
end
