# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1390 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.39.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.39.0/astro_1.39.0_darwin_arm64.tar.gz"
      sha256 "29dcdce099cb30056bd899c6189da6c6cafbdae1249363141e7abc2cc47816c5"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.39.0/astro_1.39.0_darwin_amd64.tar.gz"
      sha256 "5188a8c85ee567ec2752a61b07b5f2b0b3b0d6f49cff945bb3e0143c1b70cc94"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.39.0/astro_1.39.0_linux_arm64.tar.gz"
      sha256 "e613c31bf1685af44060cf5e09c85c4e20f195d72d9660a6a19afcddc7c7a713"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.39.0/astro_1.39.0_linux_amd64.tar.gz"
      sha256 "27bf046c70f8d0da9b482ae4975dd2cbc2f4214d867a1dcf300e03646939a2b4"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
