# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1330 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.33.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.0/astro_1.33.0_darwin_arm64.tar.gz"
      sha256 "ea8541c3940f0f035f6a154df05a0b78741fd015f9c9aecdb78dea1b1b1373a3"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.0/astro_1.33.0_darwin_amd64.tar.gz"
      sha256 "d2aa31c6162a806a60295551ea67a52f72346d97f55231e6ef02539a4ad7662b"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.0/astro_1.33.0_linux_arm64.tar.gz"
      sha256 "15973e53bc7cb3a2bb14b01d0a51be109341299fb738f3dcc05d25a40c551b69"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.33.0/astro_1.33.0_linux_amd64.tar.gz"
      sha256 "a90efd6b48dfb3889c7ae928ca0b2822e363b8ea56061413c74ef470075e2860"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
