# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0282 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "0.28.2"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.2/astro_0.28.2_darwin_arm64.tar.gz"
        sha256 "19119678c4ceed67546327cf5fd6a405716318f7bd1925e18b2e68be955a08f8"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.2/astro_0.28.2_darwin_amd64.tar.gz"
        sha256 "be077759b5e7beb5a5cb777ccba62446a2c9df542a5f3db637beadc65c8b0cfd"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.2/astro_0.28.2_linux_arm64.tar.gz"
        sha256 "50ba5a985811d75f659e556d59ad883fc3fe7d749b260abb68a97906d7af84f1"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.28.2/astro_0.28.2_linux_amd64.tar.gz"
        sha256 "8544171c31961e9dbd455d0cbfd4a1170ddd7c710a23c468358023d165da6105"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
