# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1421 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.42.1"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.1/astro_1.42.1_darwin_arm64.tar.gz"
      sha256 "87c25a9652b420f47c067a80671cdf48bfc6607f2dc13d198a6f75addc34c026"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.1/astro_1.42.1_darwin_amd64.tar.gz"
      sha256 "5346b505c5bb63dbe96092cc385716cc3f0106519df3c8e49e6b647498c6366d"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.1/astro_1.42.1_linux_arm64.tar.gz"
      sha256 "ebd0eb3feab0c0264d6bd36961ce60d677b822e90feb68a6716e20a570ff2738"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.42.1/astro_1.42.1_linux_amd64.tar.gz"
      sha256 "79619cf506aa03b01f389f8c83e314d8bbab29db51350d95adf259bd102b1d5a"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
