# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1141 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.1/astro_1.14.1_darwin_arm64.tar.gz"
        sha256 "720c3043687d57ccdf040e355087d7001797d7e9ec1b776c8de49b33ee6bbb2c"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.1/astro_1.14.1_darwin_amd64.tar.gz"
        sha256 "9177a80e59109ea61f7865dc566a167d5ca68552b980812ad5373ff13754910d"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.1/astro_1.14.1_linux_arm64.tar.gz"
        sha256 "a459707d8574a34af2d416260610fb0029d392cbbae229dae4c06045597766c5"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.1/astro_1.14.1_linux_amd64.tar.gz"
        sha256 "f066362719f032e61767c0030575e49ec8c4d85aba6f1facb4ef7eb96d6e5a46"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
