# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1170 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.17.0/astro_1.17.0_darwin_arm64.tar.gz"
        sha256 "a3c17ab4c117c9f8088184e68f489a6a1d38b7280eeb2415c132b67c41bce5b9"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.17.0/astro_1.17.0_darwin_amd64.tar.gz"
        sha256 "313489f7b30f2a18ceca0db4fc56ef59556541055d07c2fce00d772f337a8741"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.17.0/astro_1.17.0_linux_arm64.tar.gz"
        sha256 "b3a1aa38325008c4eb9bd35d398ce1ad1b33bdd20c360ad4f32bdc1fa9a8d387"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.17.0/astro_1.17.0_linux_amd64.tar.gz"
        sha256 "87470729d29e0d7f07b424e8df2fc30d724550a5378abe28ed3158e0a376f079"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
