# This file was generated by GoReleaser. DO NOT EDIT.
class AT0150 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.15.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.15.0/astro_0.15.0_darwin_amd64.tar.gz"
    sha256 "6c4bc539f76902d906abd000612b4499245c0960a49ba3874766db5ebfc863e7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.15.0/astro_0.15.0_linux_386.tar.gz"
      sha256 "664fc5d7844a00ff1da17f1ff13889c0138a3b4ae4f66007cc5ddb54f14deeac"
    end
  end
  
  depends_on "go"

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
