# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0221 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.22.1"

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.22.1/astro_0.22.1_darwin_amd64.tar.gz"
    sha256 "de23a134546da5b55b08c7d58099f29cf6cae983eb387025d6b2622176ccff5a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.22.1/astro_0.22.1_linux_amd64.tar.gz"
      sha256 "bb1eb62d10bd0ec0a2fac0780ffde75a0ba2024631616933cee8fd1c86cfef9b"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
