# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1380 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.38.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.0/astro_1.38.0_darwin_arm64.tar.gz"
      sha256 "2c1048dabd35a155ee2a6cf4db1913e2bcce1d99bc80852ac20cc13f102f34c1"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.0/astro_1.38.0_darwin_amd64.tar.gz"
      sha256 "093e32570c8e40db0ea79c889c97e311d291e10de6a3fc3b1c591f556161bb0f"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.0/astro_1.38.0_linux_arm64.tar.gz"
      sha256 "9e3972cd3dff4d059b38dc59c71a08f739db1a6aafb9b542bd2ab90a64138bbd"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.0/astro_1.38.0_linux_amd64.tar.gz"
      sha256 "56a321c76157acb50268525dd5ee2bf699c1748f81f26e86652f2f002364c2ab"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
