# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0262 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.26.2"

  on_macos do
    url "https://github.com/astronomer/astro-cli/releases/download/v0.26.2/astro_0.26.2_darwin_amd64.tar.gz"
    sha256 "b69566d143f6fb6cd651e7d0ebba1882113cccd4918ae2dc4552b1c49cb2ca00"
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.26.2/astro_0.26.2_linux_amd64.tar.gz"
      sha256 "a8069a3f9e08bc8d5504a677027fbd9c599ea0b8adf092505aa446e3555f93d5"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
