# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0261 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.26.1"

  on_macos do
    url "https://github.com/astronomer/astro-cli/releases/download/v0.26.1/astro_0.26.1_darwin_amd64.tar.gz"
    sha256 "7bf7d9d911bcf9ed462775748f0de4fee0904c8ab66d42591081b06d0e30401c"
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.26.1/astro_0.26.1_linux_amd64.tar.gz"
      sha256 "e72ba9a6da46c5fae2c5463987c6c4b03f932d7d710bf324586656a5f77450fa"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
