# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0220 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.22.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.22.0/astro_0.22.0_darwin_amd64.tar.gz"
    sha256 "f20a3df872a4b999fe3383e1d640b4d31cb42e89929008a2094f860768546549"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.22.0/astro_0.22.0_linux_amd64.tar.gz"
      sha256 "c33a51c948a8986b814c2031fea55926b7ddc156f8ed192de50592cf1554fda3"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
