# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1160 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.0/astro_1.16.0_darwin_arm64.tar.gz"
        sha256 "21a840e25fbb6eda79c2b56f610d79e7d33bce7e090d515e0e345812d9ccf0d5"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.0/astro_1.16.0_darwin_amd64.tar.gz"
        sha256 "d4c6292abf021027b191d81e09f7538fa748b34be1eb900be3c19a6ca785b14e"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.0/astro_1.16.0_linux_arm64.tar.gz"
        sha256 "40aa96d9a5762006e6107281a80456ee57221294ca8b7e1626d4b63a6cbb6a63"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.0/astro_1.16.0_linux_amd64.tar.gz"
        sha256 "070e7555b515189d6261188626d108dea91ec67ca7e17e96e9541fa0ec1a5915"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
