# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1401 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.40.1"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.1/astro_1.40.1_darwin_arm64.tar.gz"
      sha256 "78a845fd500c353a5ca811b57c5b51866da5061109c05bd658b3cd299922f74d"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.1/astro_1.40.1_darwin_amd64.tar.gz"
      sha256 "9da0b5537d46cf2ce9e6787705c0018c0dd77f2411f5f7c471d92a1937aadff7"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.1/astro_1.40.1_linux_arm64.tar.gz"
      sha256 "e20d5c3244b00783a3a46209c6bf621fdf8398452d5b72cfa760884a4166ba5f"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.1/astro_1.40.1_linux_amd64.tar.gz"
      sha256 "92adb2d32357963f51c0577bc8210279189c3c5924faf86ce765c30fdef45156"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
