# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT160 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "1.6.0"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.6.0/astro_1.6.0_darwin_arm64.tar.gz"
        sha256 "79f9c587b841ccf132f7f13efe7b262e1504bf0c46181f584d6c907455308759"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.6.0/astro_1.6.0_darwin_amd64.tar.gz"
        sha256 "ea67581a207b1a20d193e8ff87db5f2990e583b48c1014e898201c94852fee0c"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.6.0/astro_1.6.0_linux_arm64.tar.gz"
        sha256 "01ceaa38ebf2c1f7d1d59304bec5b72758de03c5dcf11371e554bf14a2e2ae36"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.6.0/astro_1.6.0_linux_amd64.tar.gz"
        sha256 "d526beb3e59640703cbc017d5884649f2d0475eb67c7f694cb6bbd8d15d8dfbb"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
