# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0180 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.18.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.18.0/astro_0.18.0_darwin_amd64.tar.gz"
    sha256 "bdc0dc39e41202f5d2fbec0363acb72ee8e7d3dc45fda365e6ba6d5b9eccfb40"
  elsif OS.linux?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.18.0/astro_0.18.0_linux_amd64.tar.gz"  
      sha256 "b0e9e1a26e9bfce36ecc0170b126316d67f9ac4a20a85c8fadb69dc72550805d"
    else
      url "https://github.com/astronomer/astro-cli/releases/download/v0.18.0/astro_0.18.0_linux_386.tar.gz"
      sha256 "bb04f6027da2414fdd4e29e9f25fde8e47721fb30add14ba42c4f6990312756d"
    end
  end
  
  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
