# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT150 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "1.5.0"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.5.0/astro_1.5.0_darwin_arm64.tar.gz"
        sha256 "94598b8378f24a086eb751130bf7d8f0780d6b6868003809b5623a72bb8d110e"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.5.0/astro_1.5.0_darwin_amd64.tar.gz"
        sha256 "89167f58f3bc372929a67aa4f3139bb5ca3560e07211da4a711c784763e22c02"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.5.0/astro_1.5.0_linux_arm64.tar.gz"
        sha256 "f8440b5d6da08aeb97ec90846227c7d3065b4f3cb894913e6bf7af784d3dbfe2"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.5.0/astro_1.5.0_linux_amd64.tar.gz"
        sha256 "b8fe245ddd44cfbad3ada67b2cc8850515433b4ae3e1295778002f9e9135f48b"  
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
