# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1161 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.1/astro_1.16.1_darwin_arm64.tar.gz"
        sha256 "3ffe0b499497f1c595d79dc2d3d91cf63d5033f86bcb6c46fbbf6c9d7a3eb617"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.1/astro_1.16.1_darwin_amd64.tar.gz"
        sha256 "8600f97f2569b760658d3a20cd181c2d2a35d59c905b3012f695b61630b5bcaa"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.1/astro_1.16.1_linux_arm64.tar.gz"
        sha256 "2d87246b2697554c0556881c55afe7ceae4d9874d1b73a3977497e3b2f047415"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.16.1/astro_1.16.1_linux_amd64.tar.gz"
        sha256 "85a64b829551829c048b56da545251d6d23f1dd00aaf3bdec8a92cfcca3b49d9"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
