# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0234 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.23.4"

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.23.4/astro_0.23.4_darwin_amd64.tar.gz"
    sha256 "7e19fe5478490e7aa6c097c60a542042a360a9bb4436353573bbc7282236a42d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.23.4/astro_0.23.4_linux_amd64.tar.gz"
      sha256 "581d5cbe79398e60d670a3e7a350b425a23864c9c77d7ec2ff14e0cf3cd96e30"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
