# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0232 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.23.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.23.2/astro_0.23.2_darwin_amd64.tar.gz"
    sha256 "8f699056df4dd0241fcbbd88b33ba8f592c49102c1fe93a2332db9fe5af0c9b4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.23.2/astro_0.23.2_linux_amd64.tar.gz"
      sha256 "4b538b6661e1bfe8b73107c55cc1708d0eac0f791096842a3e92e4555e705fc9"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
