# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1400 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.40.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.0/astro_1.40.0_darwin_arm64.tar.gz"
      sha256 "710d75eed2c32021d218aad7317fb48695c095714c14d8ce6d096102d905d0d5"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.0/astro_1.40.0_darwin_amd64.tar.gz"
      sha256 "5b13bbc450df0f6c0d9869ef0135877c88c1330369595b9245e3e5a949d95faf"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.0/astro_1.40.0_linux_arm64.tar.gz"
      sha256 "c9fcd77ee6716258f3528b5db57827c941e081dd62d0162eee5d80289c21b4ba"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.40.0/astro_1.40.0_linux_amd64.tar.gz"
      sha256 "1db27019dae6863986f01c8c2773fd9b1d0cfca01d70e2f8200caf2cbc355448"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
