# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1430 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.43.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.43.0/astro_1.43.0_darwin_arm64.tar.gz"
      sha256 "69b1bc015c7eee263a8267145c87cd7b45fe96242ad8946016f00f745d2e53eb"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.43.0/astro_1.43.0_darwin_amd64.tar.gz"
      sha256 "ddd8bc8f26ccff95d4a1fab5c690c5b683e3c8e516b9bd2a743c236d38b71707"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.43.0/astro_1.43.0_linux_arm64.tar.gz"
      sha256 "bb028608fe5ff9c3dd83cd368db6e69a862a23af7e99cf0c770f21227968d06e"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.43.0/astro_1.43.0_linux_amd64.tar.gz"
      sha256 "bfea7dbe66fb3bb5594ffe632902f89ddf5ed5bd94603f3a3403463de40164b5"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
