# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0273 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "0.27.3"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.3/astro_0.27.3_darwin_arm64.tar.gz"
        sha256 "fc007ceb4d1796ef4dead1c9fcca06a519c80a03d8216198e7624d4d4aa51f41"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.3/astro_0.27.3_darwin_amd64.tar.gz"
        sha256 "a13d3c78805cb390528eb3ad4223017499280c1f1573f19ebb2446cf452020ee"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.3/astro_0.27.3_linux_arm64.tar.gz"
        sha256 "3f4710bc3f0e6fbd00b210bccdcf2f3c3a18c36ca6c594e9e4d3a85ebf89ee43"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.3/astro_0.27.3_linux_amd64.tar.gz"
        sha256 "242364a565170b6418b6f71f1b540183dceecb3321c36caf51f8e2ced9c4483a"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
  