# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT180 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "1.8.0"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.0/astro_1.8.0_darwin_arm64.tar.gz"
        sha256 "6ec6552df5ed49c5d0b5dd4843ca1b5d46e44dc80cd65ed31d53362f6a369580"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.0/astro_1.8.0_darwin_amd64.tar.gz"
        sha256 "b51d05668afb45a81337110978c8dba4de7e14d2ed053ead708682cec0fee561"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.0/astro_1.8.0_linux_arm64.tar.gz"
        sha256 "fc219678f75f3bdb62f80fd0d678fd4fcb2595cddd4052f224ac39111cfacfa7"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.8.0/astro_1.8.0_linux_amd64.tar.gz"
        sha256 "af210b3324aa9fde86fc64d6d30023a3078e786584ad7a36d69e616b0447abc2"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
