# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astro < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.18.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.18.1/astro_1.18.1_darwin_arm64.tar.gz"
      sha256 "cce7dc613292143055f044987b26d04a5f7edf71ddb5e2e67f5aa340188e6aa3"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.18.1/astro_1.18.1_darwin_amd64.tar.gz"
      sha256 "f5942744746accdc52e66205dbb0d8bc602020dd3b27faf858d5b50b2ef089ab"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.18.1/astro_1.18.1_linux_arm64.tar.gz"
      sha256 "5588bf6b156368c91de8877ab031d684786c875111f03b48576ba8a8fd193b95"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.18.1/astro_1.18.1_linux_amd64.tar.gz"
      sha256 "51e812a29871f398ba9068e043d75ea65159666bff4d04f21129665813d9ec17"
    end
  end

  def install
    bin.install "astro"
  end


  test do
    system "#{bin}/astro version"
  end
end
