# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1340 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.34.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.34.0/astro_1.34.0_darwin_arm64.tar.gz"
      sha256 "6933e3f5db3e4e71f3a170e9dbff1eb72e59fc0e8c713e149e552b25fa7f1122"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.34.0/astro_1.34.0_darwin_amd64.tar.gz"
      sha256 "9f7bbbe4f608d66199ca70b7e3d294bc4f591283a0a4767dea91a9df6bb5143d"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.34.0/astro_1.34.0_linux_arm64.tar.gz"
      sha256 "f6f717f6df20995bf3aaa7088b36b3a6a23466e2916aa9fc6e6caa4900bbc54c"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.34.0/astro_1.34.0_linux_amd64.tar.gz"
      sha256 "040ccde91c451b67ee174823e818a889ea493dc50a4ed244e3cdea30ce581eff"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
