# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0274 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "0.27.4"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.4/astro_0.27.4_darwin_arm64.tar.gz"
        sha256 "79fe9ef9385ad7c1e458ae7ee0335177ca924db22529daecd8748e4b18402d9f"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.4/astro_0.27.4_darwin_amd64.tar.gz"
        sha256 "ff69759df19d3600da8bc9dacbc8a348d1646030dd187b128d194de052c6e067"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.4/astro_0.27.4_linux_arm64.tar.gz"
        sha256 "d268c106bf5dbfa9c293da9ee1e1ddb2033330841532d1d9d8b73dcbcce0597e"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v0.27.4/astro_0.27.4_linux_amd64.tar.gz"
        sha256 "d8fb361f91dffcf8d3577e5649bb2cc529c118dbe203577dda06e114e896fe92"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
  