# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1201 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.20.1/astro_1.20.1_darwin_arm64.tar.gz"
        sha256 "730626b371626ea3d24c27c3b503a28cd8f1b68d4ba8cfc1fe4d6a38b26acb65"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.20.1/astro_1.20.1_darwin_amd64.tar.gz"
        sha256 "ec0c66517a2796880d6d9953778a03e38cb459c79aa75a3d7800593e96616064"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.20.1/astro_1.20.1_linux_arm64.tar.gz"
        sha256 "9801d630b5cda385fd3b75ba219d712632d60cf9c771de790667833c9fb50c2a"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.20.1/astro_1.20.1_linux_amd64.tar.gz"
        sha256 "e10ab717415d7ce6ad0cfffd114a5ee62bd237992ef288e249eb5bbbf13e2448"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
