# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT131 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "1.3.1"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.3.1/astro_1.3.1_darwin_arm64.tar.gz"
        sha256 "1b9d3251cae01ff0e3b41abec7f114770e61208cd690bd90bea1b06e96ab7e9c"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.3.1/astro_1.3.1_darwin_amd64.tar.gz"
        sha256 "9c78273b2e79c08fb4d1cc23314b6965db85d7d615353deafdf01d957836e0d6"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.3.1/astro_1.3.1_linux_arm64.tar.gz"
        sha256 "7c08181f6c4d5a36c57457b130006a75203c802322205554d6f106d900af8ead"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.3.1/astro_1.3.1_linux_amd64.tar.gz"
        sha256 "0fe4c8f08906d0c612b7b083272008b657e8f055778c35861ce2ef8bd928101f"  
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
