# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1130 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.13.0/astro_1.13.0_darwin_arm64.tar.gz"
        sha256 "8c999c2c46b7b354e80cf454b68afbe4d6db16f77dc31d67facb01e810bf83ab"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.13.0/astro_1.13.0_darwin_amd64.tar.gz"
        sha256 "c859847a221432150fba81010449ba79b69e61b591b3e63b9e9fa22d0db113a0"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.13.0/astro_1.13.0_linux_arm64.tar.gz"
        sha256 "c7e17f4934fcb8a87f3f6e4a94d47782b7f014217190058acd7fdaadf85719f6"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.13.0/astro_1.13.0_linux_amd64.tar.gz"
        sha256 "d963409561bd1fff606c4a83d463010e84159d504b90ab2139666b0e17dde136"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
