# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT102 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
    version "1.0.2"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.0.2/astro_1.0.2_darwin_arm64.tar.gz"
        sha256 "be7f10996ec37160369d35c6b22de166ddae3ce7a8166a793142c35dad83153a"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.0.2/astro_1.0.2_darwin_amd64.tar.gz"
        sha256 "6debf0342b8c250c5ae4976647fa7ef6ea5af01f38121d1918cb5a5f9aa59f9b"
      end
    end

    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.0.2/astro_1.0.2_linux_arm64.tar.gz"
        sha256 "c21d04e4e15b28d39a5f14b15e47b37c5aa4e5987b56bbb68898605a709fde4f"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.0.2/astro_1.0.2_linux_amd64.tar.gz"
        sha256 "b68bc8bf3937ec0fe7954f91b4bbd0dcdf54a27620c920656247fd8da6665505"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
