# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT0170 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.17.0"

  if OS.mac?
    url "https://github.com/astronomer/astro-cli/releases/download/v0.17.0/astro_0.17.0_darwin_amd64.tar.gz"
    sha256 "2762ddfc5a0f67c9842ef7e82c12c9bc96760c59dcfb17cd6eab24d5268a1aa0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v0.17.0/astro_0.17.0_linux_386.tar.gz"
      sha256 "4bc0e7fe0c9c90e43a2a9471b1352829196d79924d83b0407d59d478bde6b96a"
    end
  end

  def install
    bin.install "astro"
  end

  test do
    system "#{bin}/astro version"
  end
end
