# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1140 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.0/astro_1.14.0_darwin_arm64.tar.gz"
        sha256 "55286a102012c8bdd95d8c0abcf3cc542f372d085bede1596388ac08ce82b3a0"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.0/astro_1.14.0_darwin_amd64.tar.gz"
        sha256 "a68c85d085e6dc52311fae9163c7ffd9da30914f0e2c64b8bb9d19e7cb288837"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.0/astro_1.14.0_linux_arm64.tar.gz"
        sha256 "42fa817351f79351251591defb000b341a857de25cff7926431fad0c1218df74"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.14.0/astro_1.14.0_linux_amd64.tar.gz"
        sha256 "f066362719f032e61767c0030575e49ec8c4d85aba6f1facb4ef7eb96d6e5a46"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
