# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1381 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.38.1"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.1/astro_1.38.1_darwin_arm64.tar.gz"
      sha256 "9a085bf21cac8590e335da279e7b89b2583413e88e8addc8858522c566be6515"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.1/astro_1.38.1_darwin_amd64.tar.gz"
      sha256 "89711796dda92f94513763fe5b04b7da67cb7d57c17eb55fd2c337affd9ab671"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.1/astro_1.38.1_linux_arm64.tar.gz"
      sha256 "369d8a44eba9ac797515167d84ac076d47aad3979a846c285ff50dbd2385c5f5"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.38.1/astro_1.38.1_linux_amd64.tar.gz"
      sha256 "0d54dcf1ff67c60d4b6e18743cf6db085ffb386d70572123733935e1f56bdf19"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
