# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1180 < Formula
    desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
    homepage "https://astronomer.io"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.18.0/astro_1.18.0_darwin_arm64.tar.gz"
        sha256 "69f0fa4a643fc26345377bac357608411a65a8c09848efef0411567611d454f6"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.18.0/astro_1.18.0_darwin_amd64.tar.gz"
        sha256 "2c8b1b26b96e7668325b1e1940c96da00e9554e090c50f01ce522fe0dfa190b2"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.18.0/astro_1.18.0_linux_arm64.tar.gz"
        sha256 "cf78122a319339c73bc6f4e1c47c2efc27d1a40df9d464cd15fc79dff4a13627"
      end
      if Hardware::CPU.intel?
        url "https://github.com/astronomer/astro-cli/releases/download/v1.18.0/astro_1.18.0_linux_amd64.tar.gz"
        sha256 "8dcc511829bbd2cf23ec57dd1b4a5078244640987e0871673b61749cdcc7a973"
      end
    end
  
    def install
      bin.install "astro"
    end
  
  
    test do
      system "#{bin}/astro version"
    end
  end
