# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class AstroAT1410 < Formula
  desc "To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.41.0"
  depends_on "podman" => :recommended if OS.mac?
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.41.0/astro_1.41.0_darwin_arm64.tar.gz"
      sha256 "b20c97241147f2e52a3279cf2b2db24c42d73218cd20ffe38353252e8073bf0d"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.41.0/astro_1.41.0_darwin_amd64.tar.gz"
      sha256 "14de69dc256043ddf592b7a0ccbbf21f408ada1bbc3ef559f5a0f6ff9b0d8069"
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.41.0/astro_1.41.0_linux_arm64.tar.gz"
      sha256 "31b4a4f9aba966f7c68411145d45eb2b0c3a01556791122c3e4b1a053713c447"
    end
    if Hardware::CPU.intel?
      url "https://github.com/astronomer/astro-cli/releases/download/v1.41.0/astro_1.41.0_linux_amd64.tar.gz"
      sha256 "d14bd43263610aebaae1012487bc5eaf4aeb4d0c49a37fc7eaf4f7a62f8ea153"
    end
  end
  def install
    bin.install "astro"
  end
  test do
    system "#{bin}/astro version"
  end
end
